### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by jackarivera** [RoverRobotics/roverrobotics_ros2#17]
In process of improving documentation to be worded better in spots and include more examples.

**Comment by ssharma0704** [comment]
**A) Missing LIDAR and IMU packages**
**B) Enable IMU and LIDAR**
**C) Setup the UDEV rules for the LIDAR and IMU**
**D) Update the LIDAR and IMU ports in the configuration file**
**E) Change the orientation of RPLIDAR in URDF**
**F) Change the Wheel Radius and Robot Length for the Rover-PRO**
**G) Disable TF Parameter in Rover-PRO configuration file**

**Comment by jackarivera** [comment]
Updated List:

1. Missing LIDAR and IMU packages
2. Enable IMU and LIDAR
3. Setup the UDEV rules for the LIDAR and IMU
4. Update the LIDAR and IMU ports in the configuration file
5. Add parameters and services table.

**Comment by jackarivera** [comment]
#23 Implements
